spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      m1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: bohu0812
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/edu_db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        jdbc-url: jdbc:mysql://localhost:3306/edu_db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
      m2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: bohu0812
        type: com.alibaba.druid.pool.DruidDataSource
        jdbc-url: jdbc:mysql://localhost:3306/edu_db_2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        url: jdbc:mysql://localhost:3306/edu_db_2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
      names: m1,m2
    props:
      sql:
        show: true
    sharding:
      tables:
        course:
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
          database-strategy:
            inline:
              algorithm-expression: m$->{user_id % 2 + 1}
              sharding-column: user_id
          key-generator:
            column: cid
            type: SNOWFLAKE
          table-strategy:
            inline:
              algorithm-expression: course_$->{cid % 2 + 1}
              sharding-column: cid
