server:
  port: 8081
spring:
  application:
    name: server
  profiles:
    active: mysql,redis,satoken,wecah
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true #自动将以下画线方式命名的数据库列映射到 Java 对象的驼峰式命名属性中
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bohu.pojo
#logging:
#  level:
#    com: debug  # 不加这个MyBatis Log插件不打印sql语句   trace info warn error debug
