spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/bohu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://10.211.55.8:3306/bohu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: bohu0812


