#不同的服务器，地址不同
aliyun:
  keyid: 你的
  keysecret: 你的
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucketname: shenbohu
  smsutils:
      SignName: 博虎
      templateCode:
        validate_codez: SMS_175061136 #发送短信验证码
        order_notice:  SMS_175051399



