spring:
  datasource:
    names: appstore , business
    appstore:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: bohu0812
      jdbc-url: jdbc:mysql://localhost:3306/appstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    business:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: bohu0812
      jdbc-url: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

